# Generated by Django 2.2.7 on 2019-11-14 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_auto_20191114_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basic_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
