# Generated by Django 2.2.7 on 2019-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0008_auto_20191115_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='replacements',
            field=models.ManyToManyField(blank=True, to='Recipes.Ingredient'),
        ),
    ]
