# Generated by Django 2.2.7 on 2019-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0009_Adding_replacements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
